# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ChatAppTFS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for ChatAppTFS
	pod 'Firebase/Firestore'
	pod 'Firebase/Auth'
	pod 'FirebaseFirestoreSwift'
        pod 'SwiftLint'

end
