
default_platform(:ios)

platform :ios do

  desc "Clean build project"
  lane :clean_build do
    scan(
      clean: true,
      scheme: "ChatAppTFS",
      build_for_testing: true
    )
  end

  desc "Run Tests without building"
  lane :tests_without_building do
    scan(
      scheme: "ChatAppTFS",
      test_without_building: true
    )
  end

  desc "Build and test"
  lane :build_and_test do
    clean_build
    tests_without_building
  end

end
