name: CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      env:
        ImageOS : macos11
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Running
      working-directory: ./ChatAppTFS
      run: bundle install
    - name: Build and run tests
      working-directory: ./ChatAppTFS
      run: |
        bundle exec fastlane build_and_test_scan
